// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Grades.proto

package com.sunnywu.grpc;

public interface GradesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GradesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sex = 2;</code>
   */
  java.lang.String getSex();
  /**
   * <code>string sex = 2;</code>
   */
  com.google.protobuf.ByteString
      getSexBytes();

  /**
   * <code>string in = 3;</code>
   */
  java.lang.String getIn();
  /**
   * <code>string in = 3;</code>
   */
  com.google.protobuf.ByteString
      getInBytes();
}
