// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Grades.proto

package com.sunnywu.grpc;

public interface GradesReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.GradesReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
